repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-symlinks
      - id: destroyed-symlinks
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-ast
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: detect-private-key
      - id: debug-statements
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        stages: [commit, push, manual]
  - repo: https://github.com/hhatto/autopep8
    rev: v2.3.1
    hooks:
      - id: autopep8
        args: ["-i"]
        stages: [commit, push, manual]
  - repo: https://github.com/pycqa/flake8
    rev: 7.1.0
    hooks:
      - id: flake8
        # TODO: uncomment this to enable more flake8 plugins
        # additional_dependencies:
        #   - flake8-bugbear
        #   - flake8-comprehensions
        #   - flake8-docstrings
        #   - flake8-pyi
        #   - flake8-simplify
        stages: [commit, push, manual]
        exclude: |
          (?x)(
            ^test/|
            ^docs/conf.py$
          )
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v18.1.7
    hooks:
      - id: clang-format
        stages: [commit, push, manual]
        exclude: |
          (?x)(
            ^include/triton/external/|
            ^python/triton/third_party/
          )

exclude: |
  (?x)(
    ^include/triton/external/|
    ^python/triton/third_party/
  )
